=== YkivWork/q2c-project/src/main/resources/azureservicebusmessageschema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "applicationProperties": {
            "id": "/properties/applicationProperties",
            "properties": {},
            "type": "object"
        },
        "body": {
            "id": "/properties/body",
            "type": "string"
        },
        "header": {
            "id": "/properties/header",
            "properties": {
                "deliveryCount": {
                    "id": "/properties/header/properties/deliveryCount",
                    "type": "integer"
                },
                "durable": {
                    "id": "/properties/header/properties/durable",
                    "type": "boolean"
                },
                "priority": {
                    "id": "/properties/header/properties/priority",
                    "type": "integer"
                },
                "ttl": {
                    "id": "/properties/header/properties/ttl",
                    "type": "null"
                }
            },
            "type": "object"
        },
        "properties": {
            "id": "/properties/properties",
            "properties": {
                "contentType": {
                    "id": "/properties/properties/properties/contentType",
                    "type": "null"
                },
                "correlationId": {
                    "id": "/properties/properties/properties/correlationId",
                    "type": "null"
                },
                "messageId": {
                    "id": "/properties/properties/properties/messageId",
                    "type": "string"
                },
                "replyTo": {
                    "id": "/properties/properties/properties/replyTo",
                    "type": "null"
                },
                "subject": {
                    "id": "/properties/properties/properties/subject",
                    "type": "null"
                },
                "to": {
                    "id": "/properties/properties/properties/to",
                    "type": "string"
                },
                "userId": {
                    "id": "/properties/properties/properties/userId",
                    "type": "null"
                }
            },
            "type": "object"
        }
    },
    "type": "object"
}

=== YkivWork/q2c-project/src/main/resources/azureservicebusmessage.json
{
    "applicationProperties": {},
    "header": {
        "durable": true,
        "priority": 4,
        "ttl": null,
        "deliveryCount": 0
    },
    "properties": {
        "messageId": "848dc7d3-022f-483c-a7c1-e0837c6792fa",
        "contentType": null,
        "correlationId": null,
        "to": "/merrillprojects",
        "replyTo": null,
        "userId": null,
        "subject": null
    },
    "body": ""
}
